---
# tasks file for testrole
- hosts: ubuntu
  tasks:
    - name: creating testusers
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - testuser1
        - testuser2
        - testuser3
        - testuser4
        - testuser5
